### PR TITLE
Fix for issue #37 getImages() crash

### PR DESCRIPTION
**Pull request by erocheleau**
I am making sure ProductGallery is an array, you could also validate that this array exists before using it.

### CODE REVIEW

**Comment by alexdrans** [comment]
Would you be able to add a test to verify this?

**Comment by erocheleau** [comment]
Added a test to check that `getImages()` returns undefined and doesn't throw even if ProductGallery is not present on the productData.

**Comment by erocheleau** [comment]
Is it the fix you prefer?
I made sure this was an array because it seemed like this is what your code was expecting.
You could also just return; straight up if ProductGallery doesn't exist.

**Comment by erocheleau** [comment]
Is this normal that Travis-ci seems to never complete?

**Comment by alexdrans** [comment]
@erocheleau replacing it with GitHub Actions :)

**Pull request merged**
