### PR TITLE
Tape and test coverage

### LINKED ISSUE #15: getProductManualPDFurl returns "PDFURL" instead of "ManualPDFURL"
method getProductManualPDFurl returns "PDFURL" instead of "ManualPDFURL"

`<ProductDescription ID="48068167" LongDesc="<b>Stylish 40” screen with 4K resolution and USB hub</b>\n\nThe ProLite ........" ManualPDFSize="3332489" ManualPDFURL="http://pdfs.icecat.biz/pdf/48068167-5566-manual.pdf" PDFSize="285343" PDFURL="http://pdfs.icecat.biz/pdf/48068167-5427.pdf" ShortDesc="39.5 MVA, 3 ms, 350 cd/m², 3840 x 2160, 16:9, PiP, PbP, HTCP, VESA, OSD, 3 x USB 3.0, HDMI, VGA, Black" URL="http://www.iiyama.com/gl_en/products/prolite-x4071uhsu-b1/" WarrantyInfo="" langid="1"/>`

### PR DESCRIPTION
**Pull request by alexdrans**
Big pull request here!

- Tests have been converted to [tape](http://github.com/substack/tape)
- 100% test coverage across product + service
- Fixed bugs along the way
- Fixes #15 
- Also includes xo and prettier, eslint removed

### CODE REVIEW

**Comment by GreenCore** [comment]
@alexdrans Thnx for this PR!   :smiley:

I found maybe one Low severity found at nyc@11.6.0 in the devDependencies.
Snyk does not test devDependencies by default.

Regular Expression Denial of Service (ReDoS)
https://snyk.io/test/npm/nyc?severity=high&severity=medium&severity=low

For this PR it is ok. This component is not really deployed to production and it is a Low severity,

**Comment by alexdrans** [comment]
@GreenCore before I merge this in; I see you use `TumbImg` instead of `ThumbImg`, and it's repeated in a few places. Is this intentional? I changed it to Thumb in this PR, and will need to update the README which references it.

**Comment by GreenCore** [comment]
@alexdrans "TumbImg" is a spelling mistake from me ;-)
Thanks for the correction!

**Comment by alexdrans** [comment]
@GreenCore Now supporting >=4.4.6

**Pull request merged**
